create table devices (
    id int4 generated by default as identity,
    author bytea,
    name_device varchar(2048) not null,
    primary key (id))

create table project (
    id int8 generated by default as identity,
    comments varchar(255),
    status boolean,
    title varchar(2048) not null,
    project_id int4,
    primary key (id))

create table user_role (
    user_id int8 not null,
    roles varchar(255))

create table usr (
    id int8 generated by default as identity,
    active boolean not null,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id))

alter table if exists project
    add constraint project_device_fk
    foreign key (project_id) references devices

alter table if exists user_role
    add constraint user_role_user_fk
    foreign key (user_id) references usr