create table devices (
    id int4 generated by default as identity,
    author bytea,
    name_device varchar(255),
    primary key (id))

create table project (
    id int4 generated by default as identity,
    comments varchar(255),
    status boolean,
    title varchar(255),
    project_id int4,
    primary key (id))

create table user_role (
    user_id int8 not null,
    roles varchar(255))

create table usr (
    id int8 generated by default as identity,
    active boolean not null,
    password varchar(255),
    username varchar(255),
    primary key (id))

alter table if exists project
    add constraint FK17k68ib1i3unbib80x2ffj8h9
    foreign key (project_id) references devices

alter table if exists user_role
    add constraint FKfpm8swft53ulq2hl11yplpr5
    foreign key (user_id) references usr